# Quarto and RMarkdown

R Markdown is a widely-used tool for creating automated, reproducible, and share-worthy outputs, such as reports. It can generate static or interactive outputs, in Word, pdf, html, powerpoint, and other formats.

An R Markdown script intersperces R code and text such that the script actually becomes your output document. You can create an entire formatted document, including narrative text (can be dynamic to change based on your data), tables, figures, bullets/numbers, bibliographies, etc.

Below is very upbeat 1 minute video defining R Markdown, taken from an [official beginner's guide](https://rmarkdown.rstudio.com/lesson-1.html) by the creators of RStudio. 

{{< video https://vimeo.com/178485416 >}}

[The guide](https://rmarkdown.rstudio.com/lesson-1.html) is a great resource for understanding what R Markdown is. 

**Quarto** is the new R Markdown put out by Posit, the makers of RStudio (and formerly named RStudio Inc.).
You can find a quick tutorial on Quarto [here](https://quarto.org/docs/get-started/hello/rstudio.html)

R for Data Science also has a [great chapter](https://r4ds.hadley.nz/quarto.html#quarto-basics) on Quarto. 

This entire website and all materials are written in Quarto. 
