# Additional Resources

## Other R Resources

### Resources within RStudio {.unnumbered}

**Help documentation**

Search the RStudio "Help" tab for documentation on R packages and specific functions. This is within the pane that also contains Files, Plots, and Packages (typically in the lower-right pane). As a shortcut, you can also type the name of a package or function into the R console after a question-mark to open the relevant Help page. Do not include parentheses.

For example: `?filter` or `?diagrammeR`.

**Interactive tutorials**

There are several ways to learn R interactively *within* RStudio.

RStudio itself offers a Tutorial pane that is powered by the [**learnr**](https://blog.rstudio.com/2020/02/25/rstudio-1-3-integrated-tutorials/) R package. Simply install this package and open a tutorial via the new "Tutorial" tab in the upper-right RStudio pane (which also contains Environment and History tabs).

The R package [**swirl**](https://swirlstats.com/) offers interactive courses in the R Console. Install and load this package, then run the command `swirl()` (empty parentheses) in the R console. You will see prompts appear in the Console. Respond by typing in the Console. It will guide you through a course of your choice.

### Cheatsheets {.unnumbered}

There are many PDF "cheatsheets" available on the [RStudio website](https://rstudio.com/resources/cheatsheets/), for example:

-   Factors with **forcats** package\
-   Dates and times with **lubridate** package\
-   Strings with **stringr** package\
-   iterative opertaions with **purrr** package\
-   Data import\
-   Data transformation cheatsheet with **dplyr** package\
-   R Markdown (to create documents like PDF, Word, Powerpoint...)\
-   Shiny (to build interactive web apps)\
-   Data visualization with **ggplot2** package\
-   Cartography (GIS)\
-   **leaflet** package (interactive maps)\
-   Python with R (**reticulate** package)

This is an online R resource specifically for [Excel users](https://jules32.github.io/r-for-excel-users/)

### Topic-Specific Resources

#### RMarkdown and Quarto

R Markdown is a widely-used tool for creating automated, reproducible, and share-worthy outputs, such as reports. It can generate static or interactive outputs, in Word, pdf, html, powerpoint, and other formats.

An R Markdown script intersperces R code and text such that the script actually becomes your output document. You can create an entire formatted document, including narrative text (can be dynamic to change based on your data), tables, figures, bullets/numbers, bibliographies, etc.

- The creators of RStudio have an  [official beginner's guide](https://rmarkdown.rstudio.com/lesson-1.html) on RMarkdown. 
- R for Data Science also has a [great chapter](https://r4ds.hadley.nz/quarto.html#quarto-basics) on Quarto. 
- [The definitive R Markdown guide](https://bookdown.org/yihui/rmarkdown/notebook.html)
- **Quarto** is the new R Markdown put out by Posit, the makers of RStudio (and formerly named RStudio Inc.).
You can find a quick tutorial on Quarto [here](https://quarto.org/docs/get-started/hello/rstudio.html)

#### Plotting

-   [Some great lecture slides on data visualization](https://github.com/ccb-hms/hsdm-r-course/blob/main/other_files/230712-visualization.pdf) 
-   [another plotting cheat sheet](https://biostats.w.uib.no/the-ggplot2-cheat-sheet-by-rstudio/)
-   [tidyverse ggplot basics page](https://ggplot2.tidyverse.org/reference/)\
-   [plotting continuous variables](http://www.sthda.com/english/articles/32-r-graphics-essentials/131-plot-two-continuous-variables-scatter-graph-and-alternatives/)\
-   R for Data Science pages on [data visualization](https://r4ds.had.co.nz/data-visualisation.html)
-   [graphics for communicaton](https://r4ds.had.co.nz/graphics-for-communication.html)


### Table Visualization

- The full **flextable** book is here: https://ardata-fr.github.io/flextable-book/
- The Github site is [here](https://davidgohel.github.io/flextable/)  
- A manual of all the **flextable** functions can be found [here](https://davidgohel.github.io/flextable/reference/index.html)
- A gallery of beautiful example **flextable** tables with code can be accessed [here](https://ardata.fr/en/flextable-gallery/)  


#### Data manipulation

- The Data Carpentry page on [**dplyr**](https://datacarpentry.org/R-genomics/04-dplyr.html)  
- The **tidyverse** reference pages on [group_by()](https://dplyr.tidyverse.org/reference/group_by.html) and [grouping](https://dplyr.tidyverse.org/articles/grouping.html)  
- This page on [Data manipulation](https://itsalocke.com/files/DataManipulationinR.pdf)  
- [Summarize with conditions in dplyr](https://stackoverflow.com/questions/23528862/summarize-with-conditions-in-dplyr)  
- A helpful tutorial on pivoting [tutorial](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html)
- The [tidyverse page on joins](https://dplyr.tidyverse.org/reference/join.html)  
- The [R for Data Science page on relational data](https://r4ds.had.co.nz/relational-data.html)  

#### Regression

- [These lecture notes](http://www.stat.ucla.edu/~dinov/courses_students.dir/02/Fall/STAT13.dir/STAT13_notes.html) are a good resource on regression. 

#### Surveys

- [Lecture slides on surveys](https://github.com/ccb-hms/hsdm-r-course/blob/main/other_files/Lumleysurvey-user.pdf)
- [UCLA stats page](https://stats.idre.ucla.edu/r/seminars/survey-data-analysis-with-r/)  
- [Article by Pew research for a general audeince on why we use survey weights](https://www.pewresearch.org/short-reads/2016/10/25/oversampling-is-used-to-study-small-groups-not-bias-poll-results/)

### Communities

#### Twitter {.unnumbered}

R has a vibrant twitter community where you can learn tips, shortcuts, and news - follow these accounts:

-   EpiHandbook (makers of the textbook these materials are based on) [\@epiRhandbook](https://twitter.com/epirhandbook)\
-   R Function A Day [\@rfuntionaday](https://twitter.com/rfunctionaday) is an *incredible* resource\
-   R for Data Science [\@rstats4ds](https://twitter.com/rstats4ds?lang=en)\
-   RStudio [\@RStudio](https://twitter.com/rstudio?lang=en)\
-   RStudio Tips [\@rstudiotips](https://twitter.com/rstudiotips)\
-   R-Bloggers [\@Rbloggers](https://twitter.com/Rbloggers)\
-   R-ladies [\@RLadiesGlobal](https://twitter.com/RLadiesGlobal)\
-   Hadley Wickham [\@hadleywickham](https://twitter.com/hadleywickham?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)

Also:

**#epitwitter** and **#rstats**

#### Free online resources {.unnumbered}

A definitive text is the [R for Data Science](https://r4ds.had.co.nz/) book by Garrett Grolemund and Hadley Wickham

The [R4Epis](https://r4epis.netlify.app/) project website aims to "develop standardised data cleaning, analysis and reporting tools to cover common types of outbreaks and population-based surveys that would be conducted in an MSF emergency response setting." You can find R basics training materials, templates for RMarkdown reports on outbreaks and surveys, and tutorials to help you set them up.

### Languages other than English {.unnumbered}

[Materiales de RStudio en Español](https://www.rstudio.com/collections/espanol/)

[Introduction à R et au tidyverse (Francais)](https://juba.github.io/tidyverse/index.html)
